CREATE TABLE data_stream_60secs
(
    TRANSACTIONTYPE VARCHAR(25) NULL,
    SOURCESYSTEM VARCHAR(25) NULL,
    SERVICENAME VARCHAR(25) NULL,
    PRODUCTID VARCHAR(25) NULL,
    CHANNEL VARCHAR(25) NULL,
    EVENTTIMESTAMP BIGINT NOT NULL
    DISTKEY,
    EATTIMESTAMP TIMESTAMP,
    EVENTHOUR INTEGER,
    EVENTDAY INTEGER,
    EVENTMONTH INTEGER,
    EVENTYEAR INTEGER,
    WEEKINMONTH INTEGER,
    WEEKINYEAR INTEGER,
    DAYINWEEK INTEGER,
    DAYINMONTH INTEGER,
    DAYINYEAR INTEGER,
    ISWEEKDAY BOOLEAN,
    DAYNAME VARCHAR
    (3),
    MONTHNAME VARCHAR
    (3),
    WINDOWAGGREGATE BOOLEAN,
    WINDOWSIZE INTEGER,
    ITEMCOUNT BIGINT NULL,
    AMOUNT DOUBLE PRECISION NULL
)
COMPOUND SORTKEY
    (TRANSACTIONTYPE, SOURCESYSTEM, SERVICENAME, PRODUCTID, CHANNEL, EVENTHOUR, EVENTDAY, WEEKINMONTH, EVENTMONTH, MONTHNAME);
